# Generated by Django 3.2.2 on 2021-05-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinename', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('startprice', models.FloatField()),
                ('endprice', models.FloatField()),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('useremail', models.EmailField(max_length=100)),
                ('usermobile', models.BigIntegerField()),
                ('userlocation', models.CharField(max_length=100)),
                ('medicinename', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('startprice', models.FloatField()),
                ('endprice', models.FloatField()),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('shopname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('mobile', models.BigIntegerField()),
                ('location', models.CharField(choices=[('Anantapur', 'Anantapur'), ('Chittoor', 'Chittoor'), ('East Godavari', 'East Godavari'), ('Guntur', 'Guntur'), ('Kadapa', 'Kadapa'), ('Krishna', 'Krishna'), ('Kurnool', 'Kurnool'), ('Nellore', 'Nellore'), ('Prakasam', 'Prakasam'), ('Srikakulam', 'Srikakulam'), ('Vishakapatnam', 'Vishakapatnam'), ('Viziayanagaram', 'Viziayanagaram'), ('West Godavari', 'West Godavari')], default='Anantapur', max_length=50)),
                ('experience', models.IntegerField()),
                ('deliverycharge', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('resume', models.CharField(max_length=100)),
                ('shopproofs', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('agreement', models.CharField(max_length=10)),
                ('assign', models.CharField(choices=[('False', 'False'), ('True', 'True')], default='False', max_length=30)),
            ],
        ),
    ]
