# Generated by Django 3.2.2 on 2021-05-18 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorder',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 18)),
        ),
    ]
