# Generated by Django 3.2.2 on 2021-05-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('slot', models.CharField(choices=[('9:00am - 10:30am', '9:00am - 10:30am'), ('11:00am - 12:30pm', '11:00am - 12:30pm'), ('1:00pm - 2:30pm', '1:00pm - 2:30pm'), ('3:00pm - 4:00pm', '3:00pm - 4:00pm')], default='9:00am - 10:30am', max_length=50)),
            ],
        ),
    ]
