# Generated by Django 3.2.2 on 2021-05-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthtips',
            name='causes',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='healthtips',
            name='medicine',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='healthtips',
            name='prevention',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='healthtips',
            name='problem',
            field=models.CharField(choices=[('Allergies', 'Allergies'), ('Cold and Flu', 'Cold and Flu'), ('Conjunctivitis (pink eye)', 'Conjunctivitis (pink eye)'), ('Diarrhea', 'Diarrhea'), ('Headache', 'Headache'), ('Mononucleosis', 'Mononucleosis'), ('Stomach Ache', 'Stomach Ache'), ('Nausea and Vomiting', 'Nausea and Vomiting')], default='Allergies', max_length=1000),
        ),
        migrations.AlterField(
            model_name='healthtips',
            name='symptoms',
            field=models.CharField(max_length=1000),
        ),
    ]
