# Generated by Django 3.2.2 on 2021-05-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='username',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
