# Generated by Django 3.2.2 on 2021-05-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20210518_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='feedback',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
