# Generated by Django 3.2.2 on 2021-05-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_consult_problem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consult',
            old_name='feedback',
            new_name='status',
        ),
        migrations.AddField(
            model_name='consult',
            name='doctorname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='consult',
            name='report',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='consult',
            name='slot',
            field=models.CharField(choices=[('9:00am - 10:30am', '9:00am - 10:30am'), ('11:00am - 12:30pm', '11:00am - 12:30pm'), ('1:00pm - 2:30pm', '1:00pm - 2:30pm'), ('3:00pm - 4:00pm', '3:00pm - 4:00pm')], default='9:00am - 10:30am', max_length=50),
        ),
    ]
