# Generated by Django 3.2.2 on 2021-05-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('useremail', models.EmailField(max_length=100)),
                ('usermobile', models.BigIntegerField()),
                ('userlocation', models.CharField(max_length=100)),
                ('medicinename', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('startprice', models.FloatField()),
                ('endprice', models.FloatField()),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
