# Generated by Django 3.2.2 on 2021-05-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Patient',
        ),
    ]
