# Generated by Django 3.2.2 on 2021-05-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_customer_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='report',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
